# Generated by Django 6.1.1 on 2026-09-26 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Слаг')),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('project', 'Проект'), ('business_plan', 'Бизнес-план')], max_length=30, verbose_name='Тип материала')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('sector', models.CharField(max_length=150, verbose_name='Сектор / Направление')),
                ('file_or_content', models.TextField(verbose_name='Содержимое / Ссылка на материалы (доступно для Premium)')),
                ('is_premium_only', models.BooleanField(default=True, verbose_name='Только для Premium')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название мероприятия')),
                ('event_type', models.CharField(choices=[('training', 'Тренинг / Курс'), ('conference', 'Конференция'), ('internship', 'Стажировка'), ('b2b', 'B2B ивент')], max_length=30, verbose_name='Тип мероприятия')),
                ('date_and_time', models.DateTimeField(verbose_name='Дата и время проведения')),
                ('format', models.CharField(default='Офлайн/Онлайн', max_length=50, verbose_name='Формат')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Место / Ссылка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('sector', models.CharField(blank=True, max_length=150, null=True, verbose_name='Целевой сектор')),
            ],
        ),
        migrations.CreateModel(
            name='Financing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('financing_type', models.CharField(choices=[('grant', 'Грант'), ('investment', 'Инвестиции')], max_length=20, verbose_name='Тип финансирования')),
                ('amount_description', models.CharField(max_length=255, verbose_name='Сумма / Условия')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Дедлайн')),
                ('description', models.TextField(verbose_name='Полное описание')),
                ('sector', models.CharField(blank=True, max_length=150, null=True, verbose_name='Сектор (например, с/х, IT)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Сделка завершена'),
        ),
        migrations.AddField(
            model_name='ad',
            name='what_i_offer_optional',
            field=models.TextField(blank=True, null=True, verbose_name='Я предлагаю (опционально)'),
        ),
        migrations.AddField(
            model_name='user',
            name='annual_turnover',
            field=models.CharField(blank=True, choices=[('up_to_100k', 'до 100 000'), ('up_to_500k', 'до 500 000'), ('up_to_1m', 'до 1 млн'), ('up_to_5m', 'до 5 млн'), ('up_to_10m', 'до 10 млн'), ('over_10m', 'более 10 млн')], max_length=50, null=True, verbose_name='Примерный оборот за год'),
        ),
        migrations.AddField(
            model_name='user',
            name='business_sector',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Сектор бизнеса'),
        ),
        migrations.AddField(
            model_name='user',
            name='employees_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Число сотрудников'),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.CharField(choices=[('freemium', 'Freemium'), ('premium', 'Premium')], default='freemium', max_length=20, verbose_name='Тип подписки'),
        ),
        migrations.AddField(
            model_name='user',
            name='website_or_social',
            field=models.URLField(blank=True, null=True, verbose_name='Сайт или соцсети'),
        ),
        migrations.AddField(
            model_name='user',
            name='what_i_offer',
            field=models.TextField(blank=True, null=True, verbose_name='Я предлагаю (знания, навыки, технологии)'),
        ),
        migrations.AddField(
            model_name='user',
            name='what_i_seek',
            field=models.TextField(blank=True, null=True, verbose_name='Я ищу (партнеры, инвесторы, консультации)'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL, verbose_name='Автор (Клиент)'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(verbose_name='Описание запроса'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Бюджет / Цена (сом/доллары)'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок запроса'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон / Telegram'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент / МСБ'), ('provider', 'Сервис-провайдер'), ('admin', 'Администратор')], default='client', max_length=20, verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='core.category', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='ProviderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Описание услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена от')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_services', to='core.category', verbose_name='Категория')),
                ('provider', models.ForeignKey(limit_choices_to={'role': 'provider'}, on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL, verbose_name='Провайдер')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
